import pandas as pd

# Load the data generated by the previous script
input_file = 'red_curve_data.csv'
output_file = 'processed_red_curve_data.csv'

try:
    df = pd.read_csv(input_file)
    
    # Apply the formula: 1 - (c / 3500)
    # We'll save this as a new column called 'State of Charge'
    df['State of Charge'] = 1 - (df['Capacity (mAh)'] / 3500)
    
    # Optional: Clip values to ensure they don't go below 0 if capacity > 3500
    df['State of Charge'] = df['State of Charge'].clip(lower=0)

    # Save to a new file
    df.to_csv(output_file, index=False)
    
    print(f"Processed data saved to {output_file}")
    print("\nFirst 5 rows of result:")
    print(df.head())

except FileNotFoundError:
    print(f"Error: Could not find {input_file}. Run the extraction script first.")